apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    repoURL: https://davidcharbonnier.github.io/deployments/
    targetRevision: 0.1.0
    chart: nextcloud
    helm:
      releaseName: nextcloud
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true
    syncOptions:
    - CreateNamespace=true